package com.aditi.transitflow.service;

import com.aditi.transitflow.dto.response.AgencyRevenueDto;
import com.aditi.transitflow.exception.ResourceNotFoundException;
import com.aditi.transitflow.entity.AgencyOffice;
import com.aditi.transitflow.entity.Bus;
import com.aditi.transitflow.entity.Customer;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Service interface for handling Agency-related operations.
 * Implementations of this interface interact with repositories
 * to fetch and process data.
 */
public interface AgencyService {

    /**
     * @param id the ID of the agency
     * @return list of customers belonging to the agency
     * @throws ResourceNotFoundException
     *         if the agency does not exist
     */
    List<Customer> getCustomersByAgencyId(Integer id);

    /**
     * Retrieves all offices of a given agency.
     * @param id the ID of the agency
     * @return list of agency offices
     * @throws ResourceNotFoundException
     *         if the agency does not exist
     */
    List<AgencyOffice> getOfficesByAgencyId(Integer id);

    /**
     * Retrieves all buses operated by an agency on a specific date.
     * @param agencyId the ID of the agency
     * @param tripDate the date for which buses are to be fetched
     * @return list of buses for the given agency and date
     * @throws ResourceNotFoundException
     *         if the agency does not exist
     */
    List<Bus> getBusByAgencyIdAndDate(Integer agencyId, LocalDateTime tripDate);

    /**
     * Retrieves the total revenue generated by an agency.
     * @param agencyId the ID of the agency
     * @return AgencyRevenueDto containing agency ID, name, and total revenue
     * @throws ResourceNotFoundException
     *         if the agency does not exist
     */
    AgencyRevenueDto getAgencyRevenueByAgencyId(Integer agencyId);
}