#spring:
#  application:
#    name: bus-ticket-booking
#  datasource:
#    url: jdbc:mysql://10.10.182.198:3306/busticketbooking
#    username: aditi
#    password: Root@1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#server:
#  port: 8082

spring:
  application:
    name: bus-ticket-booking

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none   # IMPORTANT: because you are using data.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always     # ensures data.sql runs

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082
