spring:
  application:
    name: bus-ticket-booking
  datasource:
    url: jdbc:mysql://localhost/busticketbooking
    username: root
    password: Priya@#123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
