spring:
  application:
    name: bus-ticket-booking
  datasource:
    url: jdbc:mysql://10.10.167.65:3306/busticketbooking
    username: aditi
    password: Root@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082