package com.aditi.transitflow.service.impl;

import com.aditi.transitflow.constants.AgencyConstants;
import com.aditi.transitflow.dto.response.AgencyRevenueDto;
import com.aditi.transitflow.entity.Agency;
import com.aditi.transitflow.entity.AgencyOffice;
import com.aditi.transitflow.entity.Bus;
import com.aditi.transitflow.entity.Customer;
import com.aditi.transitflow.exception.ResourceNotFoundException;
import com.aditi.transitflow.repository.*;
import com.aditi.transitflow.service.AgencyService;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Service implementation for handling Agency-related operations.
 * This class provides business logic for all the APIs in AgencyController
 * It validates the existence of the agency before performing any operation
 * and interacts with repository layers to retrieve and process data.
 * @author MAHI
 */
@Service
public class AgencyServiceImpl implements AgencyService {
    /**
     * Repository for accessing customer-related data.
     */
    private final CustomerRepository customerRepository;

    /**
     * Repository for accessing agency-related data.
     */
    private final AgencyRepository agencyRepository;

    /**
     * Repository for accessing agency office data.
     */
    private final AgencyOfficeRepository agencyOfficeRepository;

    /**
     * Repository for accessing bus-related data.
     */
    private final BusRepository busRepository;

    /**
     * Repository for accessing payment-related data.
     */
    private final PaymentRepository paymentRepository;

    /**
     * @param customerRepository     repository for customer operations
     * @param agencyRepository       repository for agency operations
     * @param agencyOfficeRepository repository for office operations
     * @param busRepository          repository for bus operations
     * @param paymentRepository      repository for payment operations
     */
    public AgencyServiceImpl(CustomerRepository customerRepository,
                             AgencyRepository agencyRepository,
                             AgencyOfficeRepository agencyOfficeRepository,
                             BusRepository busRepository,
                             PaymentRepository paymentRepository) {
        this.customerRepository = customerRepository;
        this.agencyRepository = agencyRepository;
        this.agencyOfficeRepository = agencyOfficeRepository;
        this.busRepository = busRepository;
        this.paymentRepository = paymentRepository;
    }

    /**
     * Fetches all customers associated with a given agency ID.
     * @param agencyId ID of the agency
     * @return List of Customer entities
     * @throws ResourceNotFoundException if the agency does not exist
     */
    @Override
    public List<Customer> getCustomersByAgencyId(Integer agencyId) {
        Optional<Agency> op = agencyRepository.findById(agencyId);
        if(!op.isPresent()) {
          throw new ResourceNotFoundException(AgencyConstants.AGENCY_NOT_FOUND + agencyId);
        }
        return customerRepository.findCustomerByAgencyId(agencyId);
    }

    /**
     * Fetches all offices associated with a given agency ID.
     * @param id ID of the agency
     * @return List of AgencyOffice entities
     * @throws ResourceNotFoundException if the agency does not exist
     */
    @Override
    public List<AgencyOffice> getOfficesByAgencyId(Integer id) {
        Optional<Agency> op = agencyRepository.findById(id);
        if(!op.isPresent()) {
            throw new ResourceNotFoundException(AgencyConstants.AGENCY_NOT_FOUND + id);
        }
        return agencyOfficeRepository.findByAgencyId(id);
    }

    /**
     * Fetches buses associated with a given agency ID and trip date.
     * @param agencyId ID of the agency
     * @param tripDate date and time of the trip
     * @return List of Bus entities
     * @throws ResourceNotFoundException if the agency does not exist
     */

    @Override
    public List<Bus> getBusByAgencyIdAndDate(Integer agencyId, LocalDateTime tripDate) {
        Optional<Agency> op = agencyRepository.findById(agencyId);
        if(!op.isPresent()) {
            throw new ResourceNotFoundException(AgencyConstants.AGENCY_NOT_FOUND + agencyId);
        }
        return busRepository.findBusesByAgencyIdAndDate(agencyId, tripDate);
    }

    /**
     * Calculates total revenue generated by a given agency.
     * @param agencyId ID of the agency
     * @return AgencyRevenueDto containing agency details and revenue
     * @throws ResourceNotFoundException if the agency does not exist
     */
    @Override
    public AgencyRevenueDto getAgencyRevenueByAgencyId(Integer agencyId) {
        Optional<Agency> op = agencyRepository.findById(agencyId);
        if(!op.isPresent()) {
            throw new ResourceNotFoundException(AgencyConstants.AGENCY_NOT_FOUND + agencyId);
        }
        AgencyRevenueDto revenueDto = new AgencyRevenueDto();
        revenueDto.setAgencyName(op.get().getName());
        revenueDto.setRevenue(paymentRepository.findRevenueByAgencyId(agencyId).getRevenue());
        revenueDto.setAgencyId(op.get().getAgencyId());
        return revenueDto;
    }
}
