package com.cg.busbooking.repository;

import com.cg.busbooking.dto.response.AgencyRevenueDto;
import com.cg.busbooking.entity.Payment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


/**
 * Repository interface for performing database operations on Payment entity.
 * This interface provides methods to:
 * - Perform basic CRUD operations using JpaRepository
 * - Fetch revenue details for a specific agency
 */
@Repository
public interface PaymentRepository extends JpaRepository<Payment, Integer> {

    /**
     * Retrieves total revenue generated by a specific agency.
     * This query calculates the sum of payment amounts for bookings
     * associated with an agency by joining Payment, Booking, Trip,
     * It returns the result in the form of AgencyRevenueDto.
     * @param agencyId the ID of the agency
     * @return AgencyRevenueDto containing agency ID, name, and total revenue
     */
    @Query("""
        SELECT new com.cg.busbooking.dto.response.AgencyRevenueDto(
                ao.agency.agencyId,ao.agency.name,
                SUM(p.amount)
            )
        FROM Payment p
        JOIN p.booking b
        JOIN b.trip t   
        JOIN t.bus bus
        JOIN bus.office ao
        WHERE ao.agency.agencyId=:agencyId
    """)
    AgencyRevenueDto findRevenueByAgencyId(@Param("agencyId") Integer agencyId);
}
